#!/bin/sh
#
# /config/scripts/dhcp-client/post-hooks.d/set-addrgroup

# To enable this script set the following variable to "yes"
RUN="yes"
TIMEOUT=30
SECONDS=0
LOCKFILE=/tmp/configdone

wait_for_lock() {
  echo $(date +%s) waiting for lock >> $logfile
  until [ -f $LOCKFILE ] || (( SECONDS++ >= TIMEOUT )); do
    echo "Lock not present, waiting" >> $logfile
    sleep 1
  done
  if [ -f /tmp/configdone ]; then
    echo "Lock appeared after $SECONDS seconds" >> $logfile
  else
    echo "Timed out" >> $logfile
    exit 1
  fi
}

if [ "$RUN" = "yes" ]; then
  if [[ _"$reason"_ == "_BOUND_" ]] ; then
    logfile=/tmp/set-addrgroup-$interface.debug
    echo "BOUND on $interface" >> $logfile
    tmpfile=$(mktemp /tmp/dhcp-script.XXXXXXXX)
    chmod -R 755 "${tmpfile}"
    echo "$tmpfile" >> $logfile
    tee  "$tmpfile" >> $logfile <<EOF
#!/usr/bin/vbash
source /opt/vyatta/etc/functions/script-template
configure
delete firewall group address-group ADDRv4_${interface}
set firewall group address-group ADDRv4_${interface} address ${new_ip_address}
commit comment "Updated address-group ADDRv4${interface} from DHCP"
save
EOF
  wait_for_lock
  sg vyattacfg -c "/usr/bin/vbash -x ${tmpfile}" >> ${logfile}
  rm $tmpfile
  fi
fi